#!/usr/bin/env perl

#  Gnome-Games Game Name Internationalizator, Mahjongg Edition
#
#  Copyright (C) 2001 Free Software Foundation.
#
#  This script is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This script is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this library; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#  Authors:
#  2006 - Richard Hoelscher <rah@rahga.com>
#  2001 - Kenneth Christiansen <kenneth@gnu.org>

open OUTFILE, ">translatable_game_names.h";

print OUTFILE <<HERE;
\/*
 * Translatable strings file generated by get_titles.pl.
 * Add this file to your project\'s POTFILES.in.
 * DO NOT compile it as part of your application.
 *\/
HERE

open(FH, "mahjongg.map");

while (<FH>) {
  if (/map name=\"(.+?)\"/) { # Let's not even pretend this can read XML.
    print OUTFILE "NC_(\"mahjongg map name\", \"$1\")\n";
  }
}
